// Package v1beta provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package v1beta

// ClientGatewayConfigurationStorage defines model for ClientGatewayConfigurationStorage.
type ClientGatewayConfigurationStorage struct {
	ConfigMapName *string `json:"configMapName,omitempty"`
	Namespace     *string `json:"namespace,omitempty"`
	SecretName    *string `json:"secretName,omitempty"`
}

// IPPoolProgress defines model for IPPoolProgress.
type IPPoolProgress struct {
	AllocatedAddresses int `json:"allocatedAddresses"`
	LinkedAddresses    int `json:"linkedAddresses"`
	UnlinkedAddresses  int `json:"unlinkedAddresses"`
}

// IPPoolSpec defines model for IPPoolSpec.
type IPPoolSpec struct {
	NumAddresses int  `json:"numAddresses"`
	Persistent   bool `json:"persistent,omitempty"`
}

// IPPoolStatus defines model for IPPoolStatus.
type IPPoolStatus struct {
	LastError *LastError      `json:"last_error,omitempty"`
	Progress  *IPPoolProgress `json:"progress,omitempty"`
}

// LastError defines model for LastError.
type LastError struct {
	Message string `json:"message"`
	Posted  string `json:"posted"`
}

// NetPeeringRequestSpec defines model for NetPeeringRequestSpec.
type NetPeeringRequestSpec struct {
	AccepterNetId   string `json:"accepterNetId"`
	AccepterOwnerId string `json:"accepterOwnerId"`
	Persistent      bool   `json:"persistent,omitempty"`
}

// NetPeeringSpec defines model for NetPeeringSpec.
type NetPeeringSpec struct {
	NetPeeringId string `json:"netPeeringId"`
}

// NetPeeringStatus defines model for NetPeeringStatus.
type NetPeeringStatus struct {
	AccepterIpRange          *string `json:"accepterIpRange,omitempty"`
	AccepterNetId            *string `json:"accepterNetId,omitempty"`
	AccepterOwnerId          *string `json:"accepterOwnerId,omitempty"`
	NetPeeringExpirationDate *string `json:"netPeeringExpirationDate,omitempty"`
	NetPeeringMessage        *string `json:"netPeeringMessage,omitempty"`
	NetPeeringState          *string `json:"netPeeringState,omitempty"`
	SourceIpRange            *string `json:"sourceIpRange,omitempty"`
	SourceNetId              *string `json:"sourceNetId,omitempty"`
	SourceOwnerId            *string `json:"sourceOwnerId,omitempty"`
}

// OOSAccessSpec defines model for OOSAccessSpec.
type OOSAccessSpec struct {
	Audit *OOSAudit `json:"audit,omitempty"`
	Iaas  *OOSIaas  `json:"iaas,omitempty"`
}

// OOSAccessStatus defines model for OOSAccessStatus.
type OOSAccessStatus struct {
	AccessModes  *string                  `json:"accessModes,omitempty"`
	EndpointURL  *string                  `json:"endpointURL,omitempty"`
	LastError    *LastError               `json:"last_error,omitempty"`
	ManagedRoles *string                  `json:"managedRoles,omitempty"`
	Roles        map[string]OOSRoleStatus `json:"roles,omitempty"`
}

// OOSAudit defines model for OOSAudit.
type OOSAudit struct {
	Readers []string `json:"readers,omitempty"`
}

// OOSIaas defines model for OOSIaas.
type OOSIaas struct {
	Readers []string `json:"readers,omitempty"`
}

// OOSRetentionStatus defines model for OOSRetentionStatus.
type OOSRetentionStatus struct {
	Days    *int    `json:"days,omitempty"`
	Enabled bool    `json:"enabled"`
	Mode    *string `json:"mode,omitempty"`
}

// OOSRoleStatus defines model for OOSRoleStatus.
type OOSRoleStatus struct {
	BucketName *string             `json:"bucketName,omitempty"`
	Readers    []string            `json:"readers,omitempty"`
	Retention  *OOSRetentionStatus `json:"retention,omitempty"`
}

// Phase2Options defines model for Phase2Options.
type Phase2Options struct {
	PreSharedKey *PreSharedKey `json:"preSharedKey,omitempty"`
}

// PreSharedKey defines model for PreSharedKey.
type PreSharedKey struct {
	SecretKey       string `json:"secretKey"`
	SecretName      string `json:"secretName"`
	SecretNamespace string `json:"secretNamespace"`
}

// VpnConnectionSpec defines model for VpnConnectionSpec.
type VpnConnectionSpec struct {
	BgpASN                            int                                `json:"bgpASN"`
	ClientGatewayConfigurationStorage *ClientGatewayConfigurationStorage `json:"clientGatewayConfigurationStorage,omitempty"`
	PublicIP                          string                             `json:"publicIP"`
	StaticRoutesOnly                  *bool                              `json:"staticRoutesOnly,omitempty"`
	VpnOptions                        *VpnOptions                        `json:"vpnOptions,omitempty"`
	VpnRoutes                         []string                           `json:"vpnRoutes,omitempty"`
}

// VpnConnectionStatus defines model for VpnConnectionStatus.
type VpnConnectionStatus struct {
	ClientGatewayId         *string `json:"clientGatewayId,omitempty"`
	ClientGatewayState      *string `json:"clientGatewayState,omitempty"`
	VirtualGatewayId        *string `json:"virtualGatewayId,omitempty"`
	VirtualGatewayLinkState *string `json:"virtualGatewayLinkState,omitempty"`
	VirtualGatewayState     *string `json:"virtualGatewayState,omitempty"`
}

// VpnOptions defines model for VpnOptions.
type VpnOptions struct {
	Phase2Options       *Phase2Options `json:"phase2Options,omitempty"`
	TunnelInsideIpRange *string        `json:"tunnelInsideIpRange,omitempty"`
}
