//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientGatewayConfigurationStorage) DeepCopyInto(out *ClientGatewayConfigurationStorage) {
	*out = *in
	if in.ConfigMapName != nil {
		in, out := &in.ConfigMapName, &out.ConfigMapName
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientGatewayConfigurationStorage.
func (in *ClientGatewayConfigurationStorage) DeepCopy() *ClientGatewayConfigurationStorage {
	if in == nil {
		return nil
	}
	out := new(ClientGatewayConfigurationStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPool) DeepCopyInto(out *IPPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPool.
func (in *IPPool) DeepCopy() *IPPool {
	if in == nil {
		return nil
	}
	out := new(IPPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPoolList) DeepCopyInto(out *IPPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IPPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPoolList.
func (in *IPPoolList) DeepCopy() *IPPoolList {
	if in == nil {
		return nil
	}
	out := new(IPPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IPPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPoolProgress) DeepCopyInto(out *IPPoolProgress) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPoolProgress.
func (in *IPPoolProgress) DeepCopy() *IPPoolProgress {
	if in == nil {
		return nil
	}
	out := new(IPPoolProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPoolSpec) DeepCopyInto(out *IPPoolSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPoolSpec.
func (in *IPPoolSpec) DeepCopy() *IPPoolSpec {
	if in == nil {
		return nil
	}
	out := new(IPPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPoolStatus) DeepCopyInto(out *IPPoolStatus) {
	*out = *in
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(LastError)
		**out = **in
	}
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = new(IPPoolProgress)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPoolStatus.
func (in *IPPoolStatus) DeepCopy() *IPPoolStatus {
	if in == nil {
		return nil
	}
	out := new(IPPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastError) DeepCopyInto(out *LastError) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastError.
func (in *LastError) DeepCopy() *LastError {
	if in == nil {
		return nil
	}
	out := new(LastError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetPeering) DeepCopyInto(out *NetPeering) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetPeering.
func (in *NetPeering) DeepCopy() *NetPeering {
	if in == nil {
		return nil
	}
	out := new(NetPeering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetPeering) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetPeeringAcceptance) DeepCopyInto(out *NetPeeringAcceptance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetPeeringAcceptance.
func (in *NetPeeringAcceptance) DeepCopy() *NetPeeringAcceptance {
	if in == nil {
		return nil
	}
	out := new(NetPeeringAcceptance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetPeeringAcceptance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetPeeringAcceptanceList) DeepCopyInto(out *NetPeeringAcceptanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetPeeringAcceptance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetPeeringAcceptanceList.
func (in *NetPeeringAcceptanceList) DeepCopy() *NetPeeringAcceptanceList {
	if in == nil {
		return nil
	}
	out := new(NetPeeringAcceptanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetPeeringAcceptanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetPeeringList) DeepCopyInto(out *NetPeeringList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetPeering, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetPeeringList.
func (in *NetPeeringList) DeepCopy() *NetPeeringList {
	if in == nil {
		return nil
	}
	out := new(NetPeeringList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetPeeringList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetPeeringRequest) DeepCopyInto(out *NetPeeringRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetPeeringRequest.
func (in *NetPeeringRequest) DeepCopy() *NetPeeringRequest {
	if in == nil {
		return nil
	}
	out := new(NetPeeringRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetPeeringRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetPeeringRequestList) DeepCopyInto(out *NetPeeringRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetPeeringRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetPeeringRequestList.
func (in *NetPeeringRequestList) DeepCopy() *NetPeeringRequestList {
	if in == nil {
		return nil
	}
	out := new(NetPeeringRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetPeeringRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetPeeringRequestSpec) DeepCopyInto(out *NetPeeringRequestSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetPeeringRequestSpec.
func (in *NetPeeringRequestSpec) DeepCopy() *NetPeeringRequestSpec {
	if in == nil {
		return nil
	}
	out := new(NetPeeringRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetPeeringSpec) DeepCopyInto(out *NetPeeringSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetPeeringSpec.
func (in *NetPeeringSpec) DeepCopy() *NetPeeringSpec {
	if in == nil {
		return nil
	}
	out := new(NetPeeringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetPeeringStatus) DeepCopyInto(out *NetPeeringStatus) {
	*out = *in
	if in.AccepterIpRange != nil {
		in, out := &in.AccepterIpRange, &out.AccepterIpRange
		*out = new(string)
		**out = **in
	}
	if in.AccepterNetId != nil {
		in, out := &in.AccepterNetId, &out.AccepterNetId
		*out = new(string)
		**out = **in
	}
	if in.AccepterOwnerId != nil {
		in, out := &in.AccepterOwnerId, &out.AccepterOwnerId
		*out = new(string)
		**out = **in
	}
	if in.NetPeeringExpirationDate != nil {
		in, out := &in.NetPeeringExpirationDate, &out.NetPeeringExpirationDate
		*out = new(string)
		**out = **in
	}
	if in.NetPeeringMessage != nil {
		in, out := &in.NetPeeringMessage, &out.NetPeeringMessage
		*out = new(string)
		**out = **in
	}
	if in.NetPeeringState != nil {
		in, out := &in.NetPeeringState, &out.NetPeeringState
		*out = new(string)
		**out = **in
	}
	if in.SourceIpRange != nil {
		in, out := &in.SourceIpRange, &out.SourceIpRange
		*out = new(string)
		**out = **in
	}
	if in.SourceNetId != nil {
		in, out := &in.SourceNetId, &out.SourceNetId
		*out = new(string)
		**out = **in
	}
	if in.SourceOwnerId != nil {
		in, out := &in.SourceOwnerId, &out.SourceOwnerId
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetPeeringStatus.
func (in *NetPeeringStatus) DeepCopy() *NetPeeringStatus {
	if in == nil {
		return nil
	}
	out := new(NetPeeringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OOSAccess) DeepCopyInto(out *OOSAccess) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OOSAccess.
func (in *OOSAccess) DeepCopy() *OOSAccess {
	if in == nil {
		return nil
	}
	out := new(OOSAccess)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OOSAccess) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OOSAccessList) DeepCopyInto(out *OOSAccessList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OOSAccess, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OOSAccessList.
func (in *OOSAccessList) DeepCopy() *OOSAccessList {
	if in == nil {
		return nil
	}
	out := new(OOSAccessList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OOSAccessList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OOSAccessSpec) DeepCopyInto(out *OOSAccessSpec) {
	*out = *in
	if in.Audit != nil {
		in, out := &in.Audit, &out.Audit
		*out = new(OOSAudit)
		(*in).DeepCopyInto(*out)
	}
	if in.Iaas != nil {
		in, out := &in.Iaas, &out.Iaas
		*out = new(OOSIaas)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OOSAccessSpec.
func (in *OOSAccessSpec) DeepCopy() *OOSAccessSpec {
	if in == nil {
		return nil
	}
	out := new(OOSAccessSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OOSAccessStatus) DeepCopyInto(out *OOSAccessStatus) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = new(string)
		**out = **in
	}
	if in.EndpointURL != nil {
		in, out := &in.EndpointURL, &out.EndpointURL
		*out = new(string)
		**out = **in
	}
	if in.LastError != nil {
		in, out := &in.LastError, &out.LastError
		*out = new(LastError)
		**out = **in
	}
	if in.ManagedRoles != nil {
		in, out := &in.ManagedRoles, &out.ManagedRoles
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make(map[string]OOSRoleStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OOSAccessStatus.
func (in *OOSAccessStatus) DeepCopy() *OOSAccessStatus {
	if in == nil {
		return nil
	}
	out := new(OOSAccessStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OOSAudit) DeepCopyInto(out *OOSAudit) {
	*out = *in
	if in.Readers != nil {
		in, out := &in.Readers, &out.Readers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OOSAudit.
func (in *OOSAudit) DeepCopy() *OOSAudit {
	if in == nil {
		return nil
	}
	out := new(OOSAudit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OOSIaas) DeepCopyInto(out *OOSIaas) {
	*out = *in
	if in.Readers != nil {
		in, out := &in.Readers, &out.Readers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OOSIaas.
func (in *OOSIaas) DeepCopy() *OOSIaas {
	if in == nil {
		return nil
	}
	out := new(OOSIaas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OOSRetentionStatus) DeepCopyInto(out *OOSRetentionStatus) {
	*out = *in
	if in.Days != nil {
		in, out := &in.Days, &out.Days
		*out = new(int)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OOSRetentionStatus.
func (in *OOSRetentionStatus) DeepCopy() *OOSRetentionStatus {
	if in == nil {
		return nil
	}
	out := new(OOSRetentionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OOSRoleStatus) DeepCopyInto(out *OOSRoleStatus) {
	*out = *in
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.Readers != nil {
		in, out := &in.Readers, &out.Readers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(OOSRetentionStatus)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OOSRoleStatus.
func (in *OOSRoleStatus) DeepCopy() *OOSRoleStatus {
	if in == nil {
		return nil
	}
	out := new(OOSRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Phase2Options) DeepCopyInto(out *Phase2Options) {
	*out = *in
	if in.PreSharedKey != nil {
		in, out := &in.PreSharedKey, &out.PreSharedKey
		*out = new(PreSharedKey)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Phase2Options.
func (in *Phase2Options) DeepCopy() *Phase2Options {
	if in == nil {
		return nil
	}
	out := new(Phase2Options)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreSharedKey) DeepCopyInto(out *PreSharedKey) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreSharedKey.
func (in *PreSharedKey) DeepCopy() *PreSharedKey {
	if in == nil {
		return nil
	}
	out := new(PreSharedKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpnConnection) DeepCopyInto(out *VpnConnection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpnConnection.
func (in *VpnConnection) DeepCopy() *VpnConnection {
	if in == nil {
		return nil
	}
	out := new(VpnConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VpnConnection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpnConnectionList) DeepCopyInto(out *VpnConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VpnConnection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpnConnectionList.
func (in *VpnConnectionList) DeepCopy() *VpnConnectionList {
	if in == nil {
		return nil
	}
	out := new(VpnConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VpnConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpnConnectionSpec) DeepCopyInto(out *VpnConnectionSpec) {
	*out = *in
	if in.ClientGatewayConfigurationStorage != nil {
		in, out := &in.ClientGatewayConfigurationStorage, &out.ClientGatewayConfigurationStorage
		*out = new(ClientGatewayConfigurationStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.StaticRoutesOnly != nil {
		in, out := &in.StaticRoutesOnly, &out.StaticRoutesOnly
		*out = new(bool)
		**out = **in
	}
	if in.VpnOptions != nil {
		in, out := &in.VpnOptions, &out.VpnOptions
		*out = new(VpnOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.VpnRoutes != nil {
		in, out := &in.VpnRoutes, &out.VpnRoutes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpnConnectionSpec.
func (in *VpnConnectionSpec) DeepCopy() *VpnConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(VpnConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpnConnectionStatus) DeepCopyInto(out *VpnConnectionStatus) {
	*out = *in
	if in.ClientGatewayId != nil {
		in, out := &in.ClientGatewayId, &out.ClientGatewayId
		*out = new(string)
		**out = **in
	}
	if in.ClientGatewayState != nil {
		in, out := &in.ClientGatewayState, &out.ClientGatewayState
		*out = new(string)
		**out = **in
	}
	if in.VirtualGatewayId != nil {
		in, out := &in.VirtualGatewayId, &out.VirtualGatewayId
		*out = new(string)
		**out = **in
	}
	if in.VirtualGatewayLinkState != nil {
		in, out := &in.VirtualGatewayLinkState, &out.VirtualGatewayLinkState
		*out = new(string)
		**out = **in
	}
	if in.VirtualGatewayState != nil {
		in, out := &in.VirtualGatewayState, &out.VirtualGatewayState
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpnConnectionStatus.
func (in *VpnConnectionStatus) DeepCopy() *VpnConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(VpnConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VpnOptions) DeepCopyInto(out *VpnOptions) {
	*out = *in
	if in.Phase2Options != nil {
		in, out := &in.Phase2Options, &out.Phase2Options
		*out = new(Phase2Options)
		(*in).DeepCopyInto(*out)
	}
	if in.TunnelInsideIpRange != nil {
		in, out := &in.TunnelInsideIpRange, &out.TunnelInsideIpRange
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VpnOptions.
func (in *VpnOptions) DeepCopy() *VpnOptions {
	if in == nil {
		return nil
	}
	out := new(VpnOptions)
	in.DeepCopyInto(out)
	return out
}
