/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta

import (
	context "context"

	oksdevv1beta "github.com/outscale/goutils/oks/apis/oks.dev/v1beta"
	scheme "github.com/outscale/goutils/oks/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// IPPoolsGetter has a method to return a IPPoolInterface.
// A group's client should implement this interface.
type IPPoolsGetter interface {
	IPPools() IPPoolInterface
}

// IPPoolInterface has methods to work with IPPool resources.
type IPPoolInterface interface {
	Create(ctx context.Context, iPPool *oksdevv1beta.IPPool, opts v1.CreateOptions) (*oksdevv1beta.IPPool, error)
	Update(ctx context.Context, iPPool *oksdevv1beta.IPPool, opts v1.UpdateOptions) (*oksdevv1beta.IPPool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, iPPool *oksdevv1beta.IPPool, opts v1.UpdateOptions) (*oksdevv1beta.IPPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*oksdevv1beta.IPPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*oksdevv1beta.IPPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *oksdevv1beta.IPPool, err error)
	IPPoolExpansion
}

// iPPools implements IPPoolInterface
type iPPools struct {
	*gentype.ClientWithList[*oksdevv1beta.IPPool, *oksdevv1beta.IPPoolList]
}

// newIPPools returns a IPPools
func newIPPools(c *OksV1betaClient) *iPPools {
	return &iPPools{
		gentype.NewClientWithList[*oksdevv1beta.IPPool, *oksdevv1beta.IPPoolList](
			"ippools",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *oksdevv1beta.IPPool { return &oksdevv1beta.IPPool{} },
			func() *oksdevv1beta.IPPoolList { return &oksdevv1beta.IPPoolList{} },
		),
	}
}
