/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta

import (
	context "context"

	oksdevv1beta "github.com/outscale/goutils/oks/apis/oks.dev/v1beta"
	scheme "github.com/outscale/goutils/oks/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NetPeeringsGetter has a method to return a NetPeeringInterface.
// A group's client should implement this interface.
type NetPeeringsGetter interface {
	NetPeerings() NetPeeringInterface
}

// NetPeeringInterface has methods to work with NetPeering resources.
type NetPeeringInterface interface {
	Create(ctx context.Context, netPeering *oksdevv1beta.NetPeering, opts v1.CreateOptions) (*oksdevv1beta.NetPeering, error)
	Update(ctx context.Context, netPeering *oksdevv1beta.NetPeering, opts v1.UpdateOptions) (*oksdevv1beta.NetPeering, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, netPeering *oksdevv1beta.NetPeering, opts v1.UpdateOptions) (*oksdevv1beta.NetPeering, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*oksdevv1beta.NetPeering, error)
	List(ctx context.Context, opts v1.ListOptions) (*oksdevv1beta.NetPeeringList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *oksdevv1beta.NetPeering, err error)
	NetPeeringExpansion
}

// netPeerings implements NetPeeringInterface
type netPeerings struct {
	*gentype.ClientWithList[*oksdevv1beta.NetPeering, *oksdevv1beta.NetPeeringList]
}

// newNetPeerings returns a NetPeerings
func newNetPeerings(c *OksV1betaClient) *netPeerings {
	return &netPeerings{
		gentype.NewClientWithList[*oksdevv1beta.NetPeering, *oksdevv1beta.NetPeeringList](
			"netpeerings",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *oksdevv1beta.NetPeering { return &oksdevv1beta.NetPeering{} },
			func() *oksdevv1beta.NetPeeringList { return &oksdevv1beta.NetPeeringList{} },
		),
	}
}
