/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta

import (
	context "context"

	oksdevv1beta "github.com/outscale/goutils/oks/apis/oks.dev/v1beta"
	scheme "github.com/outscale/goutils/oks/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NetPeeringAcceptancesGetter has a method to return a NetPeeringAcceptanceInterface.
// A group's client should implement this interface.
type NetPeeringAcceptancesGetter interface {
	NetPeeringAcceptances() NetPeeringAcceptanceInterface
}

// NetPeeringAcceptanceInterface has methods to work with NetPeeringAcceptance resources.
type NetPeeringAcceptanceInterface interface {
	Create(ctx context.Context, netPeeringAcceptance *oksdevv1beta.NetPeeringAcceptance, opts v1.CreateOptions) (*oksdevv1beta.NetPeeringAcceptance, error)
	Update(ctx context.Context, netPeeringAcceptance *oksdevv1beta.NetPeeringAcceptance, opts v1.UpdateOptions) (*oksdevv1beta.NetPeeringAcceptance, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, netPeeringAcceptance *oksdevv1beta.NetPeeringAcceptance, opts v1.UpdateOptions) (*oksdevv1beta.NetPeeringAcceptance, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*oksdevv1beta.NetPeeringAcceptance, error)
	List(ctx context.Context, opts v1.ListOptions) (*oksdevv1beta.NetPeeringAcceptanceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *oksdevv1beta.NetPeeringAcceptance, err error)
	NetPeeringAcceptanceExpansion
}

// netPeeringAcceptances implements NetPeeringAcceptanceInterface
type netPeeringAcceptances struct {
	*gentype.ClientWithList[*oksdevv1beta.NetPeeringAcceptance, *oksdevv1beta.NetPeeringAcceptanceList]
}

// newNetPeeringAcceptances returns a NetPeeringAcceptances
func newNetPeeringAcceptances(c *OksV1betaClient) *netPeeringAcceptances {
	return &netPeeringAcceptances{
		gentype.NewClientWithList[*oksdevv1beta.NetPeeringAcceptance, *oksdevv1beta.NetPeeringAcceptanceList](
			"netpeeringacceptances",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *oksdevv1beta.NetPeeringAcceptance { return &oksdevv1beta.NetPeeringAcceptance{} },
			func() *oksdevv1beta.NetPeeringAcceptanceList { return &oksdevv1beta.NetPeeringAcceptanceList{} },
		),
	}
}
