/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta

import (
	context "context"

	oksdevv1beta "github.com/outscale/goutils/oks/apis/oks.dev/v1beta"
	scheme "github.com/outscale/goutils/oks/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NetPeeringRequestsGetter has a method to return a NetPeeringRequestInterface.
// A group's client should implement this interface.
type NetPeeringRequestsGetter interface {
	NetPeeringRequests() NetPeeringRequestInterface
}

// NetPeeringRequestInterface has methods to work with NetPeeringRequest resources.
type NetPeeringRequestInterface interface {
	Create(ctx context.Context, netPeeringRequest *oksdevv1beta.NetPeeringRequest, opts v1.CreateOptions) (*oksdevv1beta.NetPeeringRequest, error)
	Update(ctx context.Context, netPeeringRequest *oksdevv1beta.NetPeeringRequest, opts v1.UpdateOptions) (*oksdevv1beta.NetPeeringRequest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, netPeeringRequest *oksdevv1beta.NetPeeringRequest, opts v1.UpdateOptions) (*oksdevv1beta.NetPeeringRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*oksdevv1beta.NetPeeringRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*oksdevv1beta.NetPeeringRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *oksdevv1beta.NetPeeringRequest, err error)
	NetPeeringRequestExpansion
}

// netPeeringRequests implements NetPeeringRequestInterface
type netPeeringRequests struct {
	*gentype.ClientWithList[*oksdevv1beta.NetPeeringRequest, *oksdevv1beta.NetPeeringRequestList]
}

// newNetPeeringRequests returns a NetPeeringRequests
func newNetPeeringRequests(c *OksV1betaClient) *netPeeringRequests {
	return &netPeeringRequests{
		gentype.NewClientWithList[*oksdevv1beta.NetPeeringRequest, *oksdevv1beta.NetPeeringRequestList](
			"netpeeringrequests",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *oksdevv1beta.NetPeeringRequest { return &oksdevv1beta.NetPeeringRequest{} },
			func() *oksdevv1beta.NetPeeringRequestList { return &oksdevv1beta.NetPeeringRequestList{} },
		),
	}
}
