/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta

import (
	context "context"

	oksdevv1beta "github.com/outscale/goutils/oks/apis/oks.dev/v1beta"
	scheme "github.com/outscale/goutils/oks/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OOSAccessesGetter has a method to return a OOSAccessInterface.
// A group's client should implement this interface.
type OOSAccessesGetter interface {
	OOSAccesses() OOSAccessInterface
}

// OOSAccessInterface has methods to work with OOSAccess resources.
type OOSAccessInterface interface {
	Create(ctx context.Context, oOSAccess *oksdevv1beta.OOSAccess, opts v1.CreateOptions) (*oksdevv1beta.OOSAccess, error)
	Update(ctx context.Context, oOSAccess *oksdevv1beta.OOSAccess, opts v1.UpdateOptions) (*oksdevv1beta.OOSAccess, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, oOSAccess *oksdevv1beta.OOSAccess, opts v1.UpdateOptions) (*oksdevv1beta.OOSAccess, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*oksdevv1beta.OOSAccess, error)
	List(ctx context.Context, opts v1.ListOptions) (*oksdevv1beta.OOSAccessList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *oksdevv1beta.OOSAccess, err error)
	OOSAccessExpansion
}

// oOSAccesses implements OOSAccessInterface
type oOSAccesses struct {
	*gentype.ClientWithList[*oksdevv1beta.OOSAccess, *oksdevv1beta.OOSAccessList]
}

// newOOSAccesses returns a OOSAccesses
func newOOSAccesses(c *OksV1betaClient) *oOSAccesses {
	return &oOSAccesses{
		gentype.NewClientWithList[*oksdevv1beta.OOSAccess, *oksdevv1beta.OOSAccessList](
			"oosaccesses",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *oksdevv1beta.OOSAccess { return &oksdevv1beta.OOSAccess{} },
			func() *oksdevv1beta.OOSAccessList { return &oksdevv1beta.OOSAccessList{} },
		),
	}
}
