/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta

import (
	context "context"

	oksdevv1beta "github.com/outscale/goutils/oks/apis/oks.dev/v1beta"
	scheme "github.com/outscale/goutils/oks/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VpnConnectionsGetter has a method to return a VpnConnectionInterface.
// A group's client should implement this interface.
type VpnConnectionsGetter interface {
	VpnConnections() VpnConnectionInterface
}

// VpnConnectionInterface has methods to work with VpnConnection resources.
type VpnConnectionInterface interface {
	Create(ctx context.Context, vpnConnection *oksdevv1beta.VpnConnection, opts v1.CreateOptions) (*oksdevv1beta.VpnConnection, error)
	Update(ctx context.Context, vpnConnection *oksdevv1beta.VpnConnection, opts v1.UpdateOptions) (*oksdevv1beta.VpnConnection, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vpnConnection *oksdevv1beta.VpnConnection, opts v1.UpdateOptions) (*oksdevv1beta.VpnConnection, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*oksdevv1beta.VpnConnection, error)
	List(ctx context.Context, opts v1.ListOptions) (*oksdevv1beta.VpnConnectionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *oksdevv1beta.VpnConnection, err error)
	VpnConnectionExpansion
}

// vpnConnections implements VpnConnectionInterface
type vpnConnections struct {
	*gentype.ClientWithList[*oksdevv1beta.VpnConnection, *oksdevv1beta.VpnConnectionList]
}

// newVpnConnections returns a VpnConnections
func newVpnConnections(c *OksV1betaClient) *vpnConnections {
	return &vpnConnections{
		gentype.NewClientWithList[*oksdevv1beta.VpnConnection, *oksdevv1beta.VpnConnectionList](
			"vpnconnections",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *oksdevv1beta.VpnConnection { return &oksdevv1beta.VpnConnection{} },
			func() *oksdevv1beta.VpnConnectionList { return &oksdevv1beta.VpnConnectionList{} },
		),
	}
}
