#!/bin/sh
# JSON files have been initially generated by this script and have been manually rewritten to improve the generated code or fill missing infomation.
# e.g. statuses are not specified in the v1beta schema.
# use with caution

version=`octl kube kubectl --cluster foo -- get crd nodepools.oks.dev -o json | jq -r '.status.storedVersions[0]'`
mkdir -p apis/oks.dev/$version
octl kube kubectl --cluster foo -- get crd nodepools.oks.dev -o json | jq --arg version "$version" '{"openapi":"1.0.1","title":"nodepool","version":$version,"components":{"schemas":{"Nodepool": .spec.versions | map(select(.name == $version))[0].schema.openAPIV3Schema}}}' > apis/oks.dev/$version/nodepool.json
version=`octl kube kubectl --cluster foo -- get crd netpeeringacceptances.oks.dev -o json | jq -r '.status.storedVersions[0]'`
mkdir -p apis/oks.dev/$version
octl kube kubectl --cluster foo -- get crd netpeeringacceptances.oks.dev -o json | jq --arg version "$version" '{"openapi":"1.0.1","title":"netpeeringacceptance","version":$version,"components":{"schemas":{"NetPeeringAcceptance": .spec.versions | map(select(.name == $version))[0].schema.openAPIV3Schema}}}' > apis/oks.dev/$version/netpeeringacceptance.json
octl kube kubectl --cluster foo -- get crd netpeeringrequests.oks.dev -o json | jq --arg version "$version" '{"openapi":"1.0.1","title":"netpeeringrequest","version":$version,"components":{"schemas":{"NetPeeringRequest": .spec.versions | map(select(.name == $version))[0].schema.openAPIV3Schema}}}' > apis/oks.dev/$version/netpeeringrequest.json
octl kube kubectl --cluster foo -- get crd netpeerings.oks.dev -o json | jq --arg version "$version" '{"openapi":"1.0.1","title":"netpeering","version":$version,"components":{"schemas":{"NetPeering": .spec.versions | map(select(.name == $version))[0].schema.openAPIV3Schema}}}' > apis/oks.dev/$version/netpeering.json
octl kube kubectl --cluster foo -- get crd ippools.oks.dev -o json | jq --arg version "$version" '{"openapi":"1.0.1","title":"ippool","version":$version,"components":{"schemas":{"IPPool": .spec.versions | map(select(.name == $version))[0].schema.openAPIV3Schema}}}' > apis/oks.dev/$version/ippool.json
octl kube kubectl --cluster foo -- get crd oosaccesses.oks.dev -o json | jq --arg version "$version" '{"openapi":"1.0.1","title":"oosaccess","version":$version,"components":{"schemas":{"OOSAccess": .spec.versions | map(select(.name == $version))[0].schema.openAPIV3Schema}}}' > apis/oks.dev/$version/oosaccess.json
octl kube kubectl --cluster foo -- get crd vpnconnections.oks.dev -o json | jq --arg version "$version" '{"openapi":"1.0.1","title":"vpnconnection","version":$version,"components":{"schemas":{"VpnConnection": .spec.versions | map(select(.name == $version))[0].schema.openAPIV3Schema}}}' > apis/oks.dev/$version/vpnconnection.json
