/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

// Package fake has the automatically generated clients.
package fake
