/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta "github.com/outscale/goutils/oks/apis/oks.dev/v1beta"
	oksdevv1beta "github.com/outscale/goutils/oks/clientset/typed/oks.dev/v1beta"
	gentype "k8s.io/client-go/gentype"
)

// fakeVpnConnections implements VpnConnectionInterface
type fakeVpnConnections struct {
	*gentype.FakeClientWithList[*v1beta.VpnConnection, *v1beta.VpnConnectionList]
	Fake *FakeOksV1beta
}

func newFakeVpnConnections(fake *FakeOksV1beta) oksdevv1beta.VpnConnectionInterface {
	return &fakeVpnConnections{
		gentype.NewFakeClientWithList[*v1beta.VpnConnection, *v1beta.VpnConnectionList](
			fake.Fake,
			"",
			v1beta.SchemeGroupVersion.WithResource("vpnconnections"),
			v1beta.SchemeGroupVersion.WithKind("VpnConnection"),
			func() *v1beta.VpnConnection { return &v1beta.VpnConnection{} },
			func() *v1beta.VpnConnectionList { return &v1beta.VpnConnectionList{} },
			func(dst, src *v1beta.VpnConnectionList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta.VpnConnectionList) []*v1beta.VpnConnection {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta.VpnConnectionList, items []*v1beta.VpnConnection) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
