/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta "github.com/outscale/goutils/oks/apis/oks.dev/v1beta"
	oksdevv1beta "github.com/outscale/goutils/oks/clientset/typed/oks.dev/v1beta"
	gentype "k8s.io/client-go/gentype"
)

// fakeIPPools implements IPPoolInterface
type fakeIPPools struct {
	*gentype.FakeClientWithList[*v1beta.IPPool, *v1beta.IPPoolList]
	Fake *FakeOksV1beta
}

func newFakeIPPools(fake *FakeOksV1beta) oksdevv1beta.IPPoolInterface {
	return &fakeIPPools{
		gentype.NewFakeClientWithList[*v1beta.IPPool, *v1beta.IPPoolList](
			fake.Fake,
			"",
			v1beta.SchemeGroupVersion.WithResource("ippools"),
			v1beta.SchemeGroupVersion.WithKind("IPPool"),
			func() *v1beta.IPPool { return &v1beta.IPPool{} },
			func() *v1beta.IPPoolList { return &v1beta.IPPoolList{} },
			func(dst, src *v1beta.IPPoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta.IPPoolList) []*v1beta.IPPool { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta.IPPoolList, items []*v1beta.IPPool) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
