/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta "github.com/outscale/goutils/oks/apis/oks.dev/v1beta"
	oksdevv1beta "github.com/outscale/goutils/oks/clientset/typed/oks.dev/v1beta"
	gentype "k8s.io/client-go/gentype"
)

// fakeNetPeeringRequests implements NetPeeringRequestInterface
type fakeNetPeeringRequests struct {
	*gentype.FakeClientWithList[*v1beta.NetPeeringRequest, *v1beta.NetPeeringRequestList]
	Fake *FakeOksV1beta
}

func newFakeNetPeeringRequests(fake *FakeOksV1beta) oksdevv1beta.NetPeeringRequestInterface {
	return &fakeNetPeeringRequests{
		gentype.NewFakeClientWithList[*v1beta.NetPeeringRequest, *v1beta.NetPeeringRequestList](
			fake.Fake,
			"",
			v1beta.SchemeGroupVersion.WithResource("netpeeringrequests"),
			v1beta.SchemeGroupVersion.WithKind("NetPeeringRequest"),
			func() *v1beta.NetPeeringRequest { return &v1beta.NetPeeringRequest{} },
			func() *v1beta.NetPeeringRequestList { return &v1beta.NetPeeringRequestList{} },
			func(dst, src *v1beta.NetPeeringRequestList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta.NetPeeringRequestList) []*v1beta.NetPeeringRequest {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta.NetPeeringRequestList, items []*v1beta.NetPeeringRequest) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
