/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta "github.com/outscale/goutils/oks/apis/oks.dev/v1beta"
	oksdevv1beta "github.com/outscale/goutils/oks/clientset/typed/oks.dev/v1beta"
	gentype "k8s.io/client-go/gentype"
)

// fakeNetPeeringAcceptances implements NetPeeringAcceptanceInterface
type fakeNetPeeringAcceptances struct {
	*gentype.FakeClientWithList[*v1beta.NetPeeringAcceptance, *v1beta.NetPeeringAcceptanceList]
	Fake *FakeOksV1beta
}

func newFakeNetPeeringAcceptances(fake *FakeOksV1beta) oksdevv1beta.NetPeeringAcceptanceInterface {
	return &fakeNetPeeringAcceptances{
		gentype.NewFakeClientWithList[*v1beta.NetPeeringAcceptance, *v1beta.NetPeeringAcceptanceList](
			fake.Fake,
			"",
			v1beta.SchemeGroupVersion.WithResource("netpeeringacceptances"),
			v1beta.SchemeGroupVersion.WithKind("NetPeeringAcceptance"),
			func() *v1beta.NetPeeringAcceptance { return &v1beta.NetPeeringAcceptance{} },
			func() *v1beta.NetPeeringAcceptanceList { return &v1beta.NetPeeringAcceptanceList{} },
			func(dst, src *v1beta.NetPeeringAcceptanceList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta.NetPeeringAcceptanceList) []*v1beta.NetPeeringAcceptance {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta.NetPeeringAcceptanceList, items []*v1beta.NetPeeringAcceptance) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
