/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta "github.com/outscale/goutils/oks/apis/oks.dev/v1beta"
	oksdevv1beta "github.com/outscale/goutils/oks/clientset/typed/oks.dev/v1beta"
	gentype "k8s.io/client-go/gentype"
)

// fakeNetPeerings implements NetPeeringInterface
type fakeNetPeerings struct {
	*gentype.FakeClientWithList[*v1beta.NetPeering, *v1beta.NetPeeringList]
	Fake *FakeOksV1beta
}

func newFakeNetPeerings(fake *FakeOksV1beta) oksdevv1beta.NetPeeringInterface {
	return &fakeNetPeerings{
		gentype.NewFakeClientWithList[*v1beta.NetPeering, *v1beta.NetPeeringList](
			fake.Fake,
			"",
			v1beta.SchemeGroupVersion.WithResource("netpeerings"),
			v1beta.SchemeGroupVersion.WithKind("NetPeering"),
			func() *v1beta.NetPeering { return &v1beta.NetPeering{} },
			func() *v1beta.NetPeeringList { return &v1beta.NetPeeringList{} },
			func(dst, src *v1beta.NetPeeringList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta.NetPeeringList) []*v1beta.NetPeering { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta.NetPeeringList, items []*v1beta.NetPeering) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
