/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta "github.com/outscale/goutils/oks/clientset/typed/oks.dev/v1beta"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeOksV1beta struct {
	*testing.Fake
}

func (c *FakeOksV1beta) IPPools() v1beta.IPPoolInterface {
	return newFakeIPPools(c)
}

func (c *FakeOksV1beta) NetPeerings() v1beta.NetPeeringInterface {
	return newFakeNetPeerings(c)
}

func (c *FakeOksV1beta) NetPeeringAcceptances() v1beta.NetPeeringAcceptanceInterface {
	return newFakeNetPeeringAcceptances(c)
}

func (c *FakeOksV1beta) NetPeeringRequests() v1beta.NetPeeringRequestInterface {
	return newFakeNetPeeringRequests(c)
}

func (c *FakeOksV1beta) OOSAccesses() v1beta.OOSAccessInterface {
	return newFakeOOSAccesses(c)
}

func (c *FakeOksV1beta) VpnConnections() v1beta.VpnConnectionInterface {
	return newFakeVpnConnections(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeOksV1beta) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
