/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta "github.com/outscale/goutils/oks/apis/oks.dev/v1beta"
	oksdevv1beta "github.com/outscale/goutils/oks/clientset/typed/oks.dev/v1beta"
	gentype "k8s.io/client-go/gentype"
)

// fakeOOSAccesses implements OOSAccessInterface
type fakeOOSAccesses struct {
	*gentype.FakeClientWithList[*v1beta.OOSAccess, *v1beta.OOSAccessList]
	Fake *FakeOksV1beta
}

func newFakeOOSAccesses(fake *FakeOksV1beta) oksdevv1beta.OOSAccessInterface {
	return &fakeOOSAccesses{
		gentype.NewFakeClientWithList[*v1beta.OOSAccess, *v1beta.OOSAccessList](
			fake.Fake,
			"",
			v1beta.SchemeGroupVersion.WithResource("oosaccesses"),
			v1beta.SchemeGroupVersion.WithKind("OOSAccess"),
			func() *v1beta.OOSAccess { return &v1beta.OOSAccess{} },
			func() *v1beta.OOSAccessList { return &v1beta.OOSAccessList{} },
			func(dst, src *v1beta.OOSAccessList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta.OOSAccessList) []*v1beta.OOSAccess { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta.OOSAccessList, items []*v1beta.OOSAccess) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
