// Code generated by MockGen. DO NOT EDIT.
// Source: generate.go
//
// Generated by this command:
//
//	mockgen -destination oks_mock.go -package mock_oks -source generate.go
//

// Package mock_oks is a generated GoMock package.
package mock_oks

import (
	context "context"
	io "io"
	reflect "reflect"

	middleware "github.com/outscale/osc-sdk-go/v3/pkg/middleware"
	oks "github.com/outscale/osc-sdk-go/v3/pkg/oks"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// CreateCluster mocks base method.
func (m *MockClient) CreateCluster(ctx context.Context, body oks.CreateClusterJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*oks.ClusterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCluster", varargs...)
	ret0, _ := ret[0].(*oks.ClusterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCluster indicates an expected call of CreateCluster.
func (mr *MockClientMockRecorder) CreateCluster(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCluster", reflect.TypeOf((*MockClient)(nil).CreateCluster), varargs...)
}

// CreateClusterWithBody mocks base method.
func (m *MockClient) CreateClusterWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*oks.ClusterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateClusterWithBody", varargs...)
	ret0, _ := ret[0].(*oks.ClusterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClusterWithBody indicates an expected call of CreateClusterWithBody.
func (mr *MockClientMockRecorder) CreateClusterWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClusterWithBody", reflect.TypeOf((*MockClient)(nil).CreateClusterWithBody), varargs...)
}

// CreateProject mocks base method.
func (m *MockClient) CreateProject(ctx context.Context, body oks.CreateProjectJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*oks.ProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateProject", varargs...)
	ret0, _ := ret[0].(*oks.ProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProject indicates an expected call of CreateProject.
func (mr *MockClientMockRecorder) CreateProject(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProject", reflect.TypeOf((*MockClient)(nil).CreateProject), varargs...)
}

// CreateProjectWithBody mocks base method.
func (m *MockClient) CreateProjectWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*oks.ProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateProjectWithBody", varargs...)
	ret0, _ := ret[0].(*oks.ProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProjectWithBody indicates an expected call of CreateProjectWithBody.
func (mr *MockClientMockRecorder) CreateProjectWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProjectWithBody", reflect.TypeOf((*MockClient)(nil).CreateProjectWithBody), varargs...)
}

// DeleteCluster mocks base method.
func (m *MockClient) DeleteCluster(ctx context.Context, clusterId string, reqEditors ...middleware.MiddlewareChainOption) (*oks.DetailResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, clusterId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteCluster", varargs...)
	ret0, _ := ret[0].(*oks.DetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCluster indicates an expected call of DeleteCluster.
func (mr *MockClientMockRecorder) DeleteCluster(ctx, clusterId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, clusterId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCluster", reflect.TypeOf((*MockClient)(nil).DeleteCluster), varargs...)
}

// DeleteProject mocks base method.
func (m *MockClient) DeleteProject(ctx context.Context, projectId string, reqEditors ...middleware.MiddlewareChainOption) (*oks.DetailResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteProject", varargs...)
	ret0, _ := ret[0].(*oks.DetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProject indicates an expected call of DeleteProject.
func (mr *MockClientMockRecorder) DeleteProject(ctx, projectId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProject", reflect.TypeOf((*MockClient)(nil).DeleteProject), varargs...)
}

// GetCPSubregions mocks base method.
func (m *MockClient) GetCPSubregions(ctx context.Context, reqEditors ...middleware.MiddlewareChainOption) (*oks.CPSubregionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCPSubregions", varargs...)
	ret0, _ := ret[0].(*oks.CPSubregionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCPSubregions indicates an expected call of GetCPSubregions.
func (mr *MockClientMockRecorder) GetCPSubregions(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCPSubregions", reflect.TypeOf((*MockClient)(nil).GetCPSubregions), varargs...)
}

// GetCluster mocks base method.
func (m *MockClient) GetCluster(ctx context.Context, clusterId string, reqEditors ...middleware.MiddlewareChainOption) (*oks.ClusterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, clusterId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCluster", varargs...)
	ret0, _ := ret[0].(*oks.ClusterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCluster indicates an expected call of GetCluster.
func (mr *MockClientMockRecorder) GetCluster(ctx, clusterId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, clusterId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCluster", reflect.TypeOf((*MockClient)(nil).GetCluster), varargs...)
}

// GetClusterTemplate mocks base method.
func (m *MockClient) GetClusterTemplate(ctx context.Context, params *oks.GetClusterTemplateParams, reqEditors ...middleware.MiddlewareChainOption) (*oks.TemplateResponseClusterInputTemplate, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetClusterTemplate", varargs...)
	ret0, _ := ret[0].(*oks.TemplateResponseClusterInputTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterTemplate indicates an expected call of GetClusterTemplate.
func (mr *MockClientMockRecorder) GetClusterTemplate(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterTemplate", reflect.TypeOf((*MockClient)(nil).GetClusterTemplate), varargs...)
}

// GetControlPlanePlans mocks base method.
func (m *MockClient) GetControlPlanePlans(ctx context.Context, reqEditors ...middleware.MiddlewareChainOption) (*oks.ControlPlanesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetControlPlanePlans", varargs...)
	ret0, _ := ret[0].(*oks.ControlPlanesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetControlPlanePlans indicates an expected call of GetControlPlanePlans.
func (mr *MockClientMockRecorder) GetControlPlanePlans(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetControlPlanePlans", reflect.TypeOf((*MockClient)(nil).GetControlPlanePlans), varargs...)
}

// GetKubeconfig mocks base method.
func (m *MockClient) GetKubeconfig(ctx context.Context, clusterId string, params *oks.GetKubeconfigParams, reqEditors ...middleware.MiddlewareChainOption) (*oks.KubeconfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, clusterId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetKubeconfig", varargs...)
	ret0, _ := ret[0].(*oks.KubeconfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubeconfig indicates an expected call of GetKubeconfig.
func (mr *MockClientMockRecorder) GetKubeconfig(ctx, clusterId, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, clusterId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubeconfig", reflect.TypeOf((*MockClient)(nil).GetKubeconfig), varargs...)
}

// GetKubeconfigWithPubkeyNACL mocks base method.
func (m *MockClient) GetKubeconfigWithPubkeyNACL(ctx context.Context, clusterId string, params *oks.GetKubeconfigWithPubkeyNACLParams, reqEditors ...middleware.MiddlewareChainOption) (*oks.KubeconfigResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, clusterId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetKubeconfigWithPubkeyNACL", varargs...)
	ret0, _ := ret[0].(*oks.KubeconfigResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubeconfigWithPubkeyNACL indicates an expected call of GetKubeconfigWithPubkeyNACL.
func (mr *MockClientMockRecorder) GetKubeconfigWithPubkeyNACL(ctx, clusterId, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, clusterId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubeconfigWithPubkeyNACL", reflect.TypeOf((*MockClient)(nil).GetKubeconfigWithPubkeyNACL), varargs...)
}

// GetKubernetesVersions mocks base method.
func (m *MockClient) GetKubernetesVersions(ctx context.Context, reqEditors ...middleware.MiddlewareChainOption) (*oks.KubernetesVersionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetKubernetesVersions", varargs...)
	ret0, _ := ret[0].(*oks.KubernetesVersionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKubernetesVersions indicates an expected call of GetKubernetesVersions.
func (mr *MockClientMockRecorder) GetKubernetesVersions(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKubernetesVersions", reflect.TypeOf((*MockClient)(nil).GetKubernetesVersions), varargs...)
}

// GetNodepoolTemplate mocks base method.
func (m *MockClient) GetNodepoolTemplate(ctx context.Context, reqEditors ...middleware.MiddlewareChainOption) (*oks.TemplateResponseNodepool, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNodepoolTemplate", varargs...)
	ret0, _ := ret[0].(*oks.TemplateResponseNodepool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodepoolTemplate indicates an expected call of GetNodepoolTemplate.
func (mr *MockClientMockRecorder) GetNodepoolTemplate(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodepoolTemplate", reflect.TypeOf((*MockClient)(nil).GetNodepoolTemplate), varargs...)
}

// GetProject mocks base method.
func (m *MockClient) GetProject(ctx context.Context, projectId string, reqEditors ...middleware.MiddlewareChainOption) (*oks.ProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProject", varargs...)
	ret0, _ := ret[0].(*oks.ProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProject indicates an expected call of GetProject.
func (mr *MockClientMockRecorder) GetProject(ctx, projectId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProject", reflect.TypeOf((*MockClient)(nil).GetProject), varargs...)
}

// GetProjectPublicIps mocks base method.
func (m *MockClient) GetProjectPublicIps(ctx context.Context, projectId string, reqEditors ...middleware.MiddlewareChainOption) (*oks.PublicIpsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProjectPublicIps", varargs...)
	ret0, _ := ret[0].(*oks.PublicIpsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectPublicIps indicates an expected call of GetProjectPublicIps.
func (mr *MockClientMockRecorder) GetProjectPublicIps(ctx, projectId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectPublicIps", reflect.TypeOf((*MockClient)(nil).GetProjectPublicIps), varargs...)
}

// GetProjectQuotas mocks base method.
func (m *MockClient) GetProjectQuotas(ctx context.Context, projectId string, reqEditors ...middleware.MiddlewareChainOption) (*oks.ProjectsProjectSchemaQuotasResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProjectQuotas", varargs...)
	ret0, _ := ret[0].(*oks.ProjectsProjectSchemaQuotasResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectQuotas indicates an expected call of GetProjectQuotas.
func (mr *MockClientMockRecorder) GetProjectQuotas(ctx, projectId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectQuotas", reflect.TypeOf((*MockClient)(nil).GetProjectQuotas), varargs...)
}

// GetProjectSnapshots mocks base method.
func (m *MockClient) GetProjectSnapshots(ctx context.Context, projectId string, reqEditors ...middleware.MiddlewareChainOption) (*oks.SnapshotsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProjectSnapshots", varargs...)
	ret0, _ := ret[0].(*oks.SnapshotsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectSnapshots indicates an expected call of GetProjectSnapshots.
func (mr *MockClientMockRecorder) GetProjectSnapshots(ctx, projectId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectSnapshots", reflect.TypeOf((*MockClient)(nil).GetProjectSnapshots), varargs...)
}

// GetProjectTemplate mocks base method.
func (m *MockClient) GetProjectTemplate(ctx context.Context, reqEditors ...middleware.MiddlewareChainOption) (*oks.TemplateResponseProjectInput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProjectTemplate", varargs...)
	ret0, _ := ret[0].(*oks.TemplateResponseProjectInput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectTemplate indicates an expected call of GetProjectTemplate.
func (mr *MockClientMockRecorder) GetProjectTemplate(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectTemplate", reflect.TypeOf((*MockClient)(nil).GetProjectTemplate), varargs...)
}

// GetQuotas mocks base method.
func (m *MockClient) GetQuotas(ctx context.Context, reqEditors ...middleware.MiddlewareChainOption) (*oks.QuotasQuotaSchemaQuotasResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetQuotas", varargs...)
	ret0, _ := ret[0].(*oks.QuotasQuotaSchemaQuotasResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuotas indicates an expected call of GetQuotas.
func (mr *MockClientMockRecorder) GetQuotas(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuotas", reflect.TypeOf((*MockClient)(nil).GetQuotas), varargs...)
}

// ListAllClusters mocks base method.
func (m *MockClient) ListAllClusters(ctx context.Context, params *oks.ListAllClustersParams, reqEditors ...middleware.MiddlewareChainOption) (*oks.ClusterResponseList, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAllClusters", varargs...)
	ret0, _ := ret[0].(*oks.ClusterResponseList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllClusters indicates an expected call of ListAllClusters.
func (mr *MockClientMockRecorder) ListAllClusters(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllClusters", reflect.TypeOf((*MockClient)(nil).ListAllClusters), varargs...)
}

// ListClustersByProjectID mocks base method.
func (m *MockClient) ListClustersByProjectID(ctx context.Context, params *oks.ListClustersByProjectIDParams, reqEditors ...middleware.MiddlewareChainOption) (*oks.ClusterResponseList, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListClustersByProjectID", varargs...)
	ret0, _ := ret[0].(*oks.ClusterResponseList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClustersByProjectID indicates an expected call of ListClustersByProjectID.
func (mr *MockClientMockRecorder) ListClustersByProjectID(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClustersByProjectID", reflect.TypeOf((*MockClient)(nil).ListClustersByProjectID), varargs...)
}

// ListProjects mocks base method.
func (m *MockClient) ListProjects(ctx context.Context, params *oks.ListProjectsParams, reqEditors ...middleware.MiddlewareChainOption) (*oks.ProjectResponseList, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListProjects", varargs...)
	ret0, _ := ret[0].(*oks.ProjectResponseList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockClientMockRecorder) ListProjects(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockClient)(nil).ListProjects), varargs...)
}

// UpdateCluster mocks base method.
func (m *MockClient) UpdateCluster(ctx context.Context, clusterId string, body oks.UpdateClusterJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*oks.ClusterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, clusterId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateCluster", varargs...)
	ret0, _ := ret[0].(*oks.ClusterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCluster indicates an expected call of UpdateCluster.
func (mr *MockClientMockRecorder) UpdateCluster(ctx, clusterId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, clusterId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCluster", reflect.TypeOf((*MockClient)(nil).UpdateCluster), varargs...)
}

// UpdateClusterWithBody mocks base method.
func (m *MockClient) UpdateClusterWithBody(ctx context.Context, clusterId, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*oks.ClusterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, clusterId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateClusterWithBody", varargs...)
	ret0, _ := ret[0].(*oks.ClusterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateClusterWithBody indicates an expected call of UpdateClusterWithBody.
func (mr *MockClientMockRecorder) UpdateClusterWithBody(ctx, clusterId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, clusterId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClusterWithBody", reflect.TypeOf((*MockClient)(nil).UpdateClusterWithBody), varargs...)
}

// UpdateProject mocks base method.
func (m *MockClient) UpdateProject(ctx context.Context, projectId string, body oks.UpdateProjectJSONRequestBody, reqEditors ...middleware.MiddlewareChainOption) (*oks.ProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProject", varargs...)
	ret0, _ := ret[0].(*oks.ProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProject indicates an expected call of UpdateProject.
func (mr *MockClientMockRecorder) UpdateProject(ctx, projectId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProject", reflect.TypeOf((*MockClient)(nil).UpdateProject), varargs...)
}

// UpdateProjectWithBody mocks base method.
func (m *MockClient) UpdateProjectWithBody(ctx context.Context, projectId, contentType string, body io.Reader, reqEditors ...middleware.MiddlewareChainOption) (*oks.ProjectResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, projectId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateProjectWithBody", varargs...)
	ret0, _ := ret[0].(*oks.ProjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProjectWithBody indicates an expected call of UpdateProjectWithBody.
func (mr *MockClientMockRecorder) UpdateProjectWithBody(ctx, projectId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, projectId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectWithBody", reflect.TypeOf((*MockClient)(nil).UpdateProjectWithBody), varargs...)
}

// UpgradeCluster mocks base method.
func (m *MockClient) UpgradeCluster(ctx context.Context, clusterId string, reqEditors ...middleware.MiddlewareChainOption) (*oks.ClusterResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, clusterId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpgradeCluster", varargs...)
	ret0, _ := ret[0].(*oks.ClusterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpgradeCluster indicates an expected call of UpgradeCluster.
func (mr *MockClientMockRecorder) UpgradeCluster(ctx, clusterId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, clusterId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpgradeCluster", reflect.TypeOf((*MockClient)(nil).UpgradeCluster), varargs...)
}
