/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "github.com/outscale/goutils/oks/clientset/typed/oks.dev/v1beta2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeOksV1beta2 struct {
	*testing.Fake
}

func (c *FakeOksV1beta2) NodePools() v1beta2.NodePoolInterface {
	return newFakeNodePools(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeOksV1beta2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
