/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta2 "github.com/outscale/goutils/oks/apis/oks.dev/v1beta2"
	oksdevv1beta2 "github.com/outscale/goutils/oks/clientset/typed/oks.dev/v1beta2"
	gentype "k8s.io/client-go/gentype"
)

// fakeNodePools implements NodePoolInterface
type fakeNodePools struct {
	*gentype.FakeClientWithList[*v1beta2.NodePool, *v1beta2.NodePoolList]
	Fake *FakeOksV1beta2
}

func newFakeNodePools(fake *FakeOksV1beta2) oksdevv1beta2.NodePoolInterface {
	return &fakeNodePools{
		gentype.NewFakeClientWithList[*v1beta2.NodePool, *v1beta2.NodePoolList](
			fake.Fake,
			"",
			v1beta2.SchemeGroupVersion.WithResource("nodepools"),
			v1beta2.SchemeGroupVersion.WithKind("NodePool"),
			func() *v1beta2.NodePool { return &v1beta2.NodePool{} },
			func() *v1beta2.NodePoolList { return &v1beta2.NodePoolList{} },
			func(dst, src *v1beta2.NodePoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta2.NodePoolList) []*v1beta2.NodePool { return gentype.ToPointerSlice(list.Items) },
			func(list *v1beta2.NodePoolList, items []*v1beta2.NodePool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
