name: 🔎 golangci-lint
description: Runs golang-ci-lint
inputs:
  working-directory:
    description: 'working directory'

runs:
  using: "composite"
  steps:
    - name: computing config path
      shell: bash
      run: |
        path=${{ github.action_path }}/.golangci.yaml
        echo "config=$path" >> $GITHUB_ENV
    - name: run golangci-lint
      uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
      with:
        version: v2.12.2
        args: --timeout=300s --config=${{ env.config }}
        only-new-issues: true
        working-directory: ${{ inputs.working-directory }}
