// Package v1beta2 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package v1beta2

// Defines values for AutoUpgradeMaintenanceWeekDay.
const (
	Fri AutoUpgradeMaintenanceWeekDay = "Fri"
	Mon AutoUpgradeMaintenanceWeekDay = "Mon"
	Sat AutoUpgradeMaintenanceWeekDay = "Sat"
	Sun AutoUpgradeMaintenanceWeekDay = "Sun"
	Thu AutoUpgradeMaintenanceWeekDay = "Thu"
	Tue AutoUpgradeMaintenanceWeekDay = "Tue"
	Wed AutoUpgradeMaintenanceWeekDay = "Wed"
)

// Valid indicates whether the value is a known member of the AutoUpgradeMaintenanceWeekDay enum.
func (e AutoUpgradeMaintenanceWeekDay) Valid() bool {
	switch e {
	case Fri:
		return true
	case Mon:
		return true
	case Sat:
		return true
	case Sun:
		return true
	case Thu:
		return true
	case Tue:
		return true
	case Wed:
		return true
	default:
		return false
	}
}

// Method to return the list of values
func (AutoUpgradeMaintenanceWeekDay) Values() []string {
	return []string{
		"Fri",
		"Mon",
		"Sat",
		"Sun",
		"Thu",
		"Tue",
		"Wed",
	}
}

// Defines values for FGPUModel.
const (
	NvidiaA100   FGPUModel = "nvidia-a100"
	NvidiaA10080 FGPUModel = "nvidia-a100-80"
	NvidiaH100   FGPUModel = "nvidia-h100"
	NvidiaL40    FGPUModel = "nvidia-l40"
	NvidiaM60    FGPUModel = "nvidia-m60"
	NvidiaP100   FGPUModel = "nvidia-p100"
	NvidiaP6     FGPUModel = "nvidia-p6"
	NvidiaV100   FGPUModel = "nvidia-v100"
)

// Valid indicates whether the value is a known member of the FGPUModel enum.
func (e FGPUModel) Valid() bool {
	switch e {
	case NvidiaA100:
		return true
	case NvidiaA10080:
		return true
	case NvidiaH100:
		return true
	case NvidiaL40:
		return true
	case NvidiaM60:
		return true
	case NvidiaP100:
		return true
	case NvidiaP6:
		return true
	case NvidiaV100:
		return true
	default:
		return false
	}
}

// Method to return the list of values
func (FGPUModel) Values() []string {
	return []string{
		"nvidia-a100",
		"nvidia-a100-80",
		"nvidia-h100",
		"nvidia-l40",
		"nvidia-m60",
		"nvidia-p100",
		"nvidia-p6",
		"nvidia-v100",
	}
}

// Defines values for NodePoolSpecFlavour.
const (
	OksDebian12       NodePoolSpecFlavour = "oks.debian12"
	OksDebian12Nvidia NodePoolSpecFlavour = "oks.debian12_nvidia"
	OksUbuntu22       NodePoolSpecFlavour = "oks.ubuntu22"
)

// Valid indicates whether the value is a known member of the NodePoolSpecFlavour enum.
func (e NodePoolSpecFlavour) Valid() bool {
	switch e {
	case OksDebian12:
		return true
	case OksDebian12Nvidia:
		return true
	case OksUbuntu22:
		return true
	default:
		return false
	}
}

// Method to return the list of values
func (NodePoolSpecFlavour) Values() []string {
	return []string{
		"oks.debian12",
		"oks.debian12_nvidia",
		"oks.ubuntu22",
	}
}

// Defines values for NodePoolSpecHelms.
const (
	GpuOperator  NodePoolSpecHelms = "gpu-operator"
	IngressNginx NodePoolSpecHelms = "ingress-nginx"
	Ollama       NodePoolSpecHelms = "ollama"
	Prometheus   NodePoolSpecHelms = "prometheus"
)

// Valid indicates whether the value is a known member of the NodePoolSpecHelms enum.
func (e NodePoolSpecHelms) Valid() bool {
	switch e {
	case GpuOperator:
		return true
	case IngressNginx:
		return true
	case Ollama:
		return true
	case Prometheus:
		return true
	default:
		return false
	}
}

// Method to return the list of values
func (NodePoolSpecHelms) Values() []string {
	return []string{
		"gpu-operator",
		"ingress-nginx",
		"ollama",
		"prometheus",
	}
}

// Defines values for VolumeType.
const (
	Gp2      VolumeType = "gp2"
	Io1      VolumeType = "io1"
	Standard VolumeType = "standard"
)

// Valid indicates whether the value is a known member of the VolumeType enum.
func (e VolumeType) Valid() bool {
	switch e {
	case Gp2:
		return true
	case Io1:
		return true
	case Standard:
		return true
	default:
		return false
	}
}

// Method to return the list of values
func (VolumeType) Values() []string {
	return []string{
		"gp2",
		"io1",
		"standard",
	}
}

// AutoUpgradeMaintenance defines model for AutoUpgradeMaintenance.
type AutoUpgradeMaintenance struct {
	DurationHours *int                           `json:"durationHours,omitempty"`
	Rrule         *string                        `json:"rrule,omitempty"`
	StartHour     *int                           `json:"startHour,omitempty"`
	WeekDay       *AutoUpgradeMaintenanceWeekDay `json:"weekDay,omitempty"`
}

// AutoUpgradeMaintenanceWeekDay defines model for AutoUpgradeMaintenance.WeekDay.
type AutoUpgradeMaintenanceWeekDay string

// FGPU defines model for FGPU.
type FGPU struct {
	K8sOperator *bool      `json:"k8s-operator,omitempty"`
	Model       *FGPUModel `json:"model,omitempty"`
}

// FGPUModel defines model for FGPU.Model.
type FGPUModel string

// NodePoolSpec defines model for NodePoolSpec.
type NodePoolSpec struct {
	AutoHealing       *bool                `json:"autoHealing,omitempty"`
	Autoscaling       *bool                `json:"autoscaling,omitempty"`
	DesiredNodes      *int                 `json:"desiredNodes,omitempty"`
	Fgpu              *FGPU                `json:"fgpu,omitempty"`
	Flavour           *NodePoolSpecFlavour `json:"flavour,omitempty"`
	Helms             []NodePoolSpecHelms  `json:"helms,omitempty"`
	IpPoolName        *string              `json:"ipPoolName,omitempty"`
	MaxNodes          *int                 `json:"maxNodes,omitempty"`
	MinNodes          *int                 `json:"minNodes,omitempty"`
	NodeAnnotations   map[string]string    `json:"nodeAnnotations,omitempty"`
	NodeLabels        map[string]string    `json:"nodeLabels,omitempty"`
	NodeType          string               `json:"nodeType"`
	PhysicalPlacement *PhysicalPlacement   `json:"physicalPlacement,omitempty"`
	Taint             *bool                `json:"taint,omitempty"`
	UpgradeStrategy   *UpgradeStrategy     `json:"upgradeStrategy,omitempty"`
	Volumes           []Volume             `json:"volumes,omitempty"`
	Zones             []string             `json:"zones,omitempty"`
}

// NodePoolSpecFlavour defines model for NodePoolSpec.Flavour.
type NodePoolSpecFlavour string

// NodePoolSpecHelms defines model for NodePoolSpec.Helms.
type NodePoolSpecHelms string

// NodePoolStatus defines model for NodePoolStatus.
type NodePoolStatus struct {
	LastError struct {
		Message string `json:"message"`
		Posted  string `json:"posted"`
	} `json:"last_error"`
	Progress struct {
		Attached     int `json:"attached"`
		Pending      int `json:"pending"`
		Ready        int `json:"ready"`
		Running      int `json:"running"`
		ShuttingDown int `json:"shutting_down"`
		Stopped      int `json:"stopped"`
		Stopping     int `json:"stopping"`
	} `json:"progress"`
	State struct {
		Expires string `json:"expires"`
		Name    string `json:"name"`
	} `json:"state"`
}

// PhysicalPlacement defines model for PhysicalPlacement.
type PhysicalPlacement struct {
	NodeAttractCluster *string `json:"nodeAttractCluster,omitempty"`
	NodeAttractServer  *string `json:"nodeAttractServer,omitempty"`
	NodeRepulseCluster *string `json:"nodeRepulseCluster,omitempty"`
	NodeRepulseServer  *string `json:"nodeRepulseServer,omitempty"`
}

// UpgradeStrategy defines model for UpgradeStrategy.
type UpgradeStrategy struct {
	AutoUpgradeEnabled     *bool                   `json:"autoUpgradeEnabled,omitempty"`
	AutoUpgradeMaintenance *AutoUpgradeMaintenance `json:"autoUpgradeMaintenance,omitempty"`
	MaxSurge               *int                    `json:"maxSurge,omitempty"`
	MaxUnavailable         *int                    `json:"maxUnavailable,omitempty"`
}

// Volume defines model for Volume.
type Volume struct {
	Device   *string    `json:"device,omitempty"`
	Dir      string     `json:"dir"`
	Iops     *int       `json:"iops,omitempty"`
	Name     *string    `json:"name,omitempty"`
	Size     int        `json:"size"`
	Snapshot *string    `json:"snapshot,omitempty"`
	Type     VolumeType `json:"type"`
}

// VolumeType defines model for Volume.Type.
type VolumeType string
