/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

type NodePoolExpansion interface{}
