/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	context "context"

	oksdevv1beta2 "github.com/outscale/goutils/oks/apis/oks.dev/v1beta2"
	scheme "github.com/outscale/goutils/oks/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// NodePoolsGetter has a method to return a NodePoolInterface.
// A group's client should implement this interface.
type NodePoolsGetter interface {
	NodePools() NodePoolInterface
}

// NodePoolInterface has methods to work with NodePool resources.
type NodePoolInterface interface {
	Create(ctx context.Context, nodePool *oksdevv1beta2.NodePool, opts v1.CreateOptions) (*oksdevv1beta2.NodePool, error)
	Update(ctx context.Context, nodePool *oksdevv1beta2.NodePool, opts v1.UpdateOptions) (*oksdevv1beta2.NodePool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, nodePool *oksdevv1beta2.NodePool, opts v1.UpdateOptions) (*oksdevv1beta2.NodePool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*oksdevv1beta2.NodePool, error)
	List(ctx context.Context, opts v1.ListOptions) (*oksdevv1beta2.NodePoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *oksdevv1beta2.NodePool, err error)
	NodePoolExpansion
}

// nodePools implements NodePoolInterface
type nodePools struct {
	*gentype.ClientWithList[*oksdevv1beta2.NodePool, *oksdevv1beta2.NodePoolList]
}

// newNodePools returns a NodePools
func newNodePools(c *OksV1beta2Client) *nodePools {
	return &nodePools{
		gentype.NewClientWithList[*oksdevv1beta2.NodePool, *oksdevv1beta2.NodePoolList](
			"nodepools",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *oksdevv1beta2.NodePool { return &oksdevv1beta2.NodePool{} },
			func() *oksdevv1beta2.NodePoolList { return &oksdevv1beta2.NodePoolList{} },
		),
	}
}
