/*
SPDX-FileCopyrightText: 2026 Outscale SAS <opensource@outscale.com>

SPDX-License-Identifier: BSD-3-Clause
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	http "net/http"

	oksdevv1beta2 "github.com/outscale/goutils/oks/apis/oks.dev/v1beta2"
	scheme "github.com/outscale/goutils/oks/clientset/scheme"
	rest "k8s.io/client-go/rest"
)

type OksV1beta2Interface interface {
	RESTClient() rest.Interface
	NodePoolsGetter
}

// OksV1beta2Client is used to interact with features provided by the oks.dev group.
type OksV1beta2Client struct {
	restClient rest.Interface
}

func (c *OksV1beta2Client) NodePools() NodePoolInterface {
	return newNodePools(c)
}

// NewForConfig creates a new OksV1beta2Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*OksV1beta2Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new OksV1beta2Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*OksV1beta2Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &OksV1beta2Client{client}, nil
}

// NewForConfigOrDie creates a new OksV1beta2Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *OksV1beta2Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new OksV1beta2Client for the given RESTClient.
func New(c rest.Interface) *OksV1beta2Client {
	return &OksV1beta2Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := oksdevv1beta2.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *OksV1beta2Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
